
services:
  users-microservice:
    container_name: users-microservice
    build:
      context: ./src/UsersService
      dockerfile: UsersService.API/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD:-MyStrongPassword}
      - DB_PASSWORD=${DB_PASSWORD:-MyStrongPassword}
      - ConnectionStrings__DefaultConnection=Host=postgres-container;Port=5432;Username=postgres;Database=eCommerceUsers
    depends_on:
      - postgres-container

  postgres-container:
    container_name: postgres-container
    image: postgres:16.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD:-MyStrongPassword}
      - POSTGRES_DB=eCommerceUsers
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d/

volumes:
  pgdata:
